In [3]:
import numpy as np;

In [7]:
#np.array takes list as an input

In [5]:
arr0 = np.array([0, 1, 2, 3]);
print arr0;

[0 1 2 3]


In [8]:
# if you want to make a matrix, you still need to pass a list but this list will contain lists as its members
mat = np.array([[1, 2, 3,4], [5,6, 7, 8]]);
print mat;

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
#matlab equivalent of size or python equivalent of len is shape
print mat.shape

(2, 4)


In [10]:
#dtype is another object present in array
print mat.dtype

int64


In [15]:
#corresponding to matlab's zeros function we have zeros function in numpy
zarr = np.zeros([2,2])
print zarr;
oarr = np.ones([4,2]);
print oarr;

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [4]:
#if you want to create an identity matrix, similar to matlab you need to use the command eye
Imat = np.eye(5);
print Imat

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


In [7]:
#similar to linspace in matlab, we have arange in numpy, np.arange(start, stop, stepsize)
ar_ex = np.arange(1, 56, 2)
print ar_ex

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53 55]


In [9]:
#by default division is integer arithmetic. So without specifying type, it would default to integer arithmetic
5/2

2

In [10]:
#If you want to remove this in python 2.0, you need to do
from __future__ import division
5/2

2.5

In [16]:
#Array Multiplications
arr1 = np.array([np.arange(12), np.arange(13,25)])
arr2 = np.array([np.arange(2, 26, 2), np.arange(2, 26, 2)])
print arr1;
print arr2

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 2  4  6  8 10 12 14 16 18 20 22 24]
 [ 2  4  6  8 10 12 14 16 18 20 22 24]]


In [17]:
#By default array multiplication is dot product
print arr1*arr2

[[  0   4  12  24  40  60  84 112 144 180 220 264]
 [ 26  56  90 128 170 216 266 320 378 440 506 576]]


In [20]:
#if the arrays are not of same size
arr1 = np.arange(12);
arr2 = np.arange(15);
print arr1*arr2;

ValueError: operands could not be broadcast together with shapes (12,) (15,) 

In [23]:
#Array Multiplications
# for dot product to happen both arrays have to be of same size
arr1 = np.array([np.arange(12), np.arange(13,25)])
arr2 = np.array(np.arange(2, 24, 2))
print arr1 * arr2;

ValueError: operands could not be broadcast together with shapes (2,12) (11,) 

In [53]:
#on each array scalar operations can be performed as in matlab
print arr1 + 1;
print arr1 * 5;
print arr1 /5;
print arr1 ** 2;
print np.sqrt(arr1)

[[ 1  2 11 16  5  6  7  8  9 10  8 12]
 [14 15 76 81 18 19 20 21 22 23 24 25]]
[[  0   5  50  75  20  25  30  35  40  45  35  55]
 [ 65  70 375 400  85  90  95 100 105 110 115 120]]
[[  0.    0.2   2.    3.    0.8   1.    1.2   1.4   1.6   1.8   1.4   2.2]
 [  2.6   2.8  15.   16.    3.4   3.6   3.8   4.    4.2   4.4   4.6   4.8]]
[[   0    1  100  225   16   25   36   49   64   81   49  121]
 [ 169  196 5625 6400  289  324  361  400  441  484  529  576]]
[[ 0.          1.          3.16227766  3.87298335  2.          2.23606798
   2.44948974  2.64575131  2.82842712  3.          2.64575131  3.31662479]
 [ 3.60555128  3.74165739  8.66025404  8.94427191  4.12310563  4.24264069
   4.35889894  4.47213595  4.58257569  4.69041576  4.79583152  4.89897949]]


In [30]:
# array indexing is done as in python lists. For example if you want to get 5th element of arr1 arr[4] 
#starts with zero. You need to give row number followed by column number
arr1[0, 5]

5

In [33]:
#array slicing is also possible as in matlab
arr1[0:2, 2:4]

array([[ 2,  3],
       [15, 16]])

In [34]:
arr1[0:2, 2:4] = arr1[0:2, 2:4] * 5;
print arr1

[[ 0  1 10 15  4  5  6  7  8  9 10 11]
 [13 14 75 80 17 18 19 20 21 22 23 24]]


In [38]:
# MOST IMPORTANT assignment of array just assigns pointer
arr2 = arr1;
arr2[0,10] = 7;
print arr1;
print arr2;

[[ 0  1 10 15  4  5  6  7  8  9  7 11]
 [13 14 75 80 17 18 19 20 21 22 23 24]]
[[ 0  1 10 15  4  5  6  7  8  9  7 11]
 [13 14 75 80 17 18 19 20 21 22 23 24]]


In [39]:
#in order to avoid this problem, you can explicitly create copies by using the function copy
arr3 = arr1.copy();
arr3[0,11] = 77;
print arr1;
print arr3;

[[ 0  1 10 15  4  5  6  7  8  9  7 11]
 [13 14 75 80 17 18 19 20 21 22 23 24]]
[[ 0  1 10 15  4  5  6  7  8  9  7 77]
 [13 14 75 80 17 18 19 20 21 22 23 24]]


In [43]:
#you can get entire row using indexing
print arr3[1,]
print arr3[:,5]

[13 14 75 80 17 18 19 20 21 22 23 24]
[ 5 18]


In [45]:
#Fancy indexing, instead of giving a numbers as arguments, you can give list as an argument
arr3[:, [5,6,9]]

array([[ 5,  6,  9],
       [18, 19, 22]])

In [47]:
#Instead of creating arrays by passing lists as arguments, you can create a unidimensional array and reshape it.
vect0 = np.arange(36)
print vect0.reshape(6,6)
#Three dimensional array
print vect0.reshape(6, 2, 3) 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]]]


In [49]:
#transposing a matrix is just calling a function T
trans_ex = vect0.reshape(6,6)
print trans_ex;
print trans_ex.T

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[[ 0  6 12 18 24 30]
 [ 1  7 13 19 25 31]
 [ 2  8 14 20 26 32]
 [ 3  9 15 21 27 33]
 [ 4 10 16 22 28 34]
 [ 5 11 17 23 29 35]]


In [50]:
#trans example
trans_ex = vect0.reshape(6, 2, 3)
trans_ex.transpose(1, 0, 2)

array([[[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]],

       [[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]]])

In [52]:
#swapaxes is a really cool example. Here axes refers to dimension
arr0 = np.arange(9).reshape(3,3)
print arr0;
print arr0.swapaxes(0, 1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [54]:
#exponential functions are created using exp as in matlab
np.exp(2)

7.3890560989306504

In [56]:
#numpy can create random arrays using random
print np.random.randn(2,2)

[[-0.18551947 -1.14861911]
 [-1.1575923  -1.62274201]]


In [65]:
#maximum and minimum functions are maximum and minimum respectively
arr0 = np.random.randn(5);
arr1 = np.random.randn(5);
print arr0;
print arr1;
print np.maximum(arr0, arr1)

[-0.00902585  0.30431186 -0.82509482  0.00327116  0.34100665]
[-0.17890411 -0.72692813  0.898959    0.16742459 -0.43823721]
[-0.00902585  0.30431186  0.898959    0.16742459  0.34100665]


In [66]:
print np.sin(np.arange(10) * np.pi /4)

[  0.00000000e+00   7.07106781e-01   1.00000000e+00   7.07106781e-01
   1.22464680e-16  -7.07106781e-01  -1.00000000e+00  -7.07106781e-01
  -2.44929360e-16   7.07106781e-01]
